name: bmf_customer
description: "BMF Myanmar ERP Microfinance - Borrower Self-Service Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & DI
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0

  # Navigation
  go_router: ^14.2.7

  # Networking & Data
  dio: ^5.7.0
  uuid: ^4.5.1
  connectivity_plus: ^6.0.5

  # Security & Biometrics
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  crypto: ^3.0.3

  # Formatting & UI
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  generate: true
