name: bmf_agent_app
description: "BMF Myanmar ERP Microfinance - Agent Field Mobile Application (Offline-First & Bluetooth Printing)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Architecture
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0

  # Routing & Navigation
  go_router: ^14.2.7

  # Networking & HTTP
  dio: ^5.7.0
  uuid: ^4.5.1
  connectivity_plus: ^6.0.5

  # Local Database & Encryption (SQLCipher AES-256)
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_secure_storage: ^9.2.2

  # Security & Biometrics
  local_auth: ^2.3.0

  # UI Components & Typography
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.20.0
  build_runner: ^2.4.12
  mockito: ^5.4.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  # fonts:
  #   - family: Pyidaungsu
  #     fonts:
  #       - asset: assets/fonts/Pyidaungsu-Regular.ttf
  #       - asset: assets/fonts/Pyidaungsu-Bold.ttf
  #         weight: 700
